name: Docker Image CI

on: [ push,  pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        cd ./server
        docker build . --file server.dockerfile --tag jskonst/web-app/server:$(date +%s)
